require 'json'
require 'net/http'

require 'dependency'
Dependency.activate
require 'telemetry/logger'
require 'uuid'
require 'clock'
require 'settings'
require 'schema'
Settings.activate
require 'casing'

require 'event_store/client/http/settings'
require 'event_store/client/http/stream/name'
require 'event_store/client/http/stream/entry'
require 'event_store/client/http/stream/slice'
require 'event_store/client/http/atom/document'
require 'event_store/client/http/event_data'
require 'event_store/client/http/subscription'
require 'event_store/client/http/write/builder'
require 'event_store/client/http/write/request'
require 'event_store/client/http/write'
require 'event_store/client/http/writer'
require 'event_store/client/http/reader'

require 'event_store/client/http/client'
require 'event_store/client/http/request'
require 'event_store/client/http/request/post'
require 'event_store/client/http/request/get'
require 'event_store/client/http/slice_reader'
